apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage portal
  # Example for optional annotations
  annotations:
    github.com/project-slug: Fatmajk/poc
spec:
  type: website
  owner: Fatmajk
  lifecycle: experimental
