apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Webstore
  annotations:
    github.com/project-slug: Fatmajk/poc
spec:
  type: website
  owner: Fatmajk
  lifecycle: experimental
