---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: poc
spec:
  owner: fatmajk
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webstore
  description: Webstore
spec:
  type: website
  lifecycle: experimental
  owner: fatmajk
  system: poc
  consumesApis: [webstore-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: webstore-api
  description: Webstore API
spec:
  type: openapi
  lifecycle: experimental
  owner: fatmajk
  system: poc
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Webstore API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080/api/v1/webstore
    paths:
      /products:
        get:
          summary: List all products
      /customers:
        get:
          summary: List all customers
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-dev
  description: The dev team
spec:
  type: team
  profile:
    displayName: Dev Team
  members: [fatmajk, bobby]
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: fatmajk
spec:
  profile:
    displayName: Michael K
  memberOf: [team-dev]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bobby
spec:
  profile:
    displayName: bob Berg
  memberOf: [team-dev]
