---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: poc
spec:
  owner: Fatmajk
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Webstore API
spec:
  type: website
  owner: Fatmajk
  system: poc
  lifecycle: experimental
  #providesApis: [example-grpc-api]
