---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: poc
spec:
  owner: dev-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webstore
  description: Webstore
  annotations:
    github.com/project-slug: fatmajk/poc
    backstage.io/techdocs-ref: dir:./docs
    #backstage.io/techdocs-ref: url:https://github.com/Fatmajk/poc/tree/main/docs
spec:
  type: website
  lifecycle: experimental
  owner: dev-team
  system: poc
  consumesApis: [webstore-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: webstore-api
  description: Webstore API
  annotations:
    github.com/project-slug: fatmajk/poc
spec:
  type: openapi
  lifecycle: experimental
  owner: user:fatmajk
  system: poc
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Webstore API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080/api/v1/webstore
    paths:
      /products:
        get:
          summary: List all products
      /customers:
        get:
          summary: List all customers
        post:
          summary: Create new customer
