apiVersion: v1
kind: System
metadata:
  name: poc
spec:
  owner: Fatmajk
---
apiVersion: v1
kind: Component
metadata:
  name: frontend
  description: Webstore
  #annotations:
    #github.com/project-slug: Fatmajk/poc
spec:
  type: website
  owner: Fatmajk
  system: poc
  lifecycle: experimental
  #providesApis: [example-grpc-api]
---
apiVersion: v2
kind: API
metadata:
  name: backend
  description: Webstore API
  #annotations:
    #github.com/project-slug: Fatmajk/poc
spec:
  type: unknown
  owner: Fatmajk
  system: poc
  lifecycle: experimental
