apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: Webstore API
  # Example for optional annotations
  annotations:
    github.com/project-slug: Fatmajk/poc
spec:
  type: API
  owner: Fatmajk
  lifecycle: experimental
