---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: poc
spec:
  owner: Fatmajk
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend
  description: Webstore API
  # Example for optional annotations
  #annotations:
    #github.com/project-slug: Fatmajk/poc
spec:
  type: API
  owner: Fatmajk
  system: poc
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: Webstore
  # Example for optional annotations
  #annotations:
    #github.com/project-slug: Fatmajk/poc
spec:
  type: website
  owner: Fatmajk
  system: poc
  lifecycle: experimental
  providesApis: [backend]
---
