apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: poc
spec:
  owner: fatmajk
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
spec:
  type: website
  lifecycle: experimental
  owner: fatmajk
  system: poc
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend
spec:
  type: grpc
  lifecycle: experimental
  owner: fatmajk
  system: poc
  
